#!/usr/bin/env python3
"""Broadcast a dynamic TF so RViz RobotModel can attach.

Prefer the NMPC/estimator state (RigidStateEstimate) when state_topic is set.
MAVROS local_position/pose is PX4 EKF in map and can sit tens of centimetres
off the VRPN/world frame that the predicted path uses.
"""
import rospy
import tf2_ros
from geometry_msgs.msg import PoseStamped, TransformStamped


def main():
    rospy.init_node("pose_to_tf")
    pose_topic = rospy.get_param("~pose_topic", "")
    state_topic = rospy.get_param("~state_topic", "")
    child_frame = rospy.get_param("~child_frame_id", "base_link")
    override_parent = rospy.get_param("~parent_frame_id", "")
    br = tf2_ros.TransformBroadcaster()

    def send(parent, position, orientation):
        tf = TransformStamped()
        tf.header.stamp = rospy.Time.now()
        tf.header.frame_id = override_parent or parent or "world"
        tf.child_frame_id = child_frame
        tf.transform.translation.x = position.x
        tf.transform.translation.y = position.y
        tf.transform.translation.z = position.z
        tf.transform.rotation = orientation
        br.sendTransform(tf)

    def on_pose(msg):
        send(msg.header.frame_id, msg.pose.position, msg.pose.orientation)

    if state_topic:
        from rigid_state_estimator_msgs.msg import RigidStateEstimate

        def on_state(msg):
            send(msg.header.frame_id or "world", msg.position, msg.orientation)

        rospy.Subscriber(state_topic, RigidStateEstimate, on_state, queue_size=20)
    elif pose_topic:
        rospy.Subscriber(pose_topic, PoseStamped, on_pose, queue_size=20)
    else:
        rospy.logfatal("set ~state_topic or ~pose_topic")
        return

    rospy.spin()


if __name__ == "__main__":
    main()
