#!/usr/bin/env python3
"""Broadcast a dynamic TF from a PoseStamped so RViz RobotModel can attach."""
import rospy
import tf2_ros
from geometry_msgs.msg import PoseStamped, TransformStamped


def main():
    rospy.init_node("pose_to_tf")
    pose_topic = rospy.get_param("~pose_topic", "mavros/local_position/pose")
    child_frame = rospy.get_param("~child_frame_id", "base_link")
    override_parent = rospy.get_param("~parent_frame_id", "")
    br = tf2_ros.TransformBroadcaster()

    def callback(msg):
        tf = TransformStamped()
        tf.header.stamp = rospy.Time.now()
        tf.header.frame_id = override_parent or msg.header.frame_id
        tf.child_frame_id = child_frame
        tf.transform.translation.x = msg.pose.position.x
        tf.transform.translation.y = msg.pose.position.y
        tf.transform.translation.z = msg.pose.position.z
        tf.transform.rotation = msg.pose.orientation
        br.sendTransform(tf)

    rospy.Subscriber(pose_topic, PoseStamped, callback, queue_size=20)
    rospy.spin()


if __name__ == "__main__":
    main()
